# Generated by Django 5.2.15 on 2026-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('readme_content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('is_github_synced', models.BooleanField(default=False)),
                ('github_repo_name', models.CharField(blank=True, max_length=200)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('deployed', 'Deployed'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='in_progress', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
