# Generated by Django 4.2.30 on 2026-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
