# Generated by Django 4.2.30 on 2026-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcases', '0002_alter_showcase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
